try {
    alert(test);
} catch (e) {
    alert(e.message);
    console.error("test");
}